apiVersion: apps/v1
kind: Deployment
metadata:
  name: digicloset-python
spec:
  template:
    spec:
      containers:
        - name: python-service
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10